[build-system]
requires = ["setuptools>=82.0.1", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["wlepmeister"]

[tool.setuptools.package-dir]
"wlepmeister" = "src"

[project]
name = "wlepmeister"
version = "4.32"
description = "Layer-based desktop graphics editor for posters, stickers, and simple brand assets."
authors = [{name = "dawidnolove", email = "dawpi007@gmail.com"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
"dnspython>=2.8.0",
"pillow>=12.0.0",
"pymongo>=4.16.0",
]

[project.scripts]
wlepmeister = "wlepmeister.main:main"
